
[tool.pyflow]
name = "pyta"
py_version = "3.9"
version = "0.1.0"
authors = ["Yair Dar <yair.dar@outlook.com>"]

[tool.pyflow.scripts]
pyta_cli = "pyta.pyta_cli:main"

[tool.pyflow.dependencies]
# loguru = "^0.6.0"
# pydantic = "^1.7.0"
# pyyaml = "^6.0"
# typer = "^0.3.2"
typer = "^0.4.0"
# typer-cli = "^0.0.12"
click = "^8.0.3"

[tool.pyflow.dev-dependencies]
# black = "^22.1.0"
# typer-cli = "^0.0.12"

